---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro
data:
  workers.yml: |
    - name: foo
      type: responder
      triggers:
        - observable:filename
        - observable:hostname
      manifest:
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: cerebro-job-
          labels:
            env: dev
        spec:
          backoffLimit: 0
          template:
            spec:
              restartPolicy: Never
              securityContext:
                runAsNonRoot: True
                runAsUser: 1000
              containers:
                - name: job
                  image: job:latest
                  #command: ["bash", "-c", "sleep infinity;"]
                  imagePullPolicy: Never
                  env:
                    - name: TH_URL
                      value: http://thehive:9000
                    - name: TH_USER # need X-TheHive header auth
                      value: service
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-runner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerebro
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cerebro
subjects:
  - kind: ServiceAccount
    name: cerebro
roleRef:
  kind: Role
  name: job-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  ports:
    - port: 8000
  selector:
    app: cerebro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      serviceAccountName: cerebro
      volumes:
        - name: workers
          configMap:
            name: cerebro
      containers:
        - name: cerebro
          image: cerebro:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: workers
              mountPath: /etc/workers.yml
              subPath: workers.yml
              readOnly: true
          env:
            - name: WORKER_CONFIG
              value: /etc/workers.yml
