---
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: cerebro
build:
  tagPolicy:
    envTemplate:
      template: dev
  artifacts:
    - image: cerebro/server
      platforms:
        - linux/amd64
      context: .
      docker:
        dockerfile: k8s/Dockerfile
    - image: cerebro/worker
      platforms:
        - linux/amd64
      context: ./neuron
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/configmap-app.yaml
    - k8s/configmap-thehive-webhook-rules.yaml
    - k8s/configmap-worker-bar.yaml
    - k8s/configmap-worker-fail.yaml
    - k8s/configmap-worker-foo.yaml
    - k8s/deployment.yaml
    - k8s/rbac.yaml
    - k8s/service.yaml
# Rewrite the worker image in the ConfigMap (see .data.worker_image).
# https://skaffold.dev/docs/tutorials/skaffold-resource-selector/
resourceSelector:
  allow:
    - groupKind: ConfigMap
      image: [".data.worker_image"]
      labels: [".*"]
