---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro
data:
  workers.yml: |
    - name: foo
      type: responder
      triggers:
        - observable:filename
        - observable:hostname
      manifest:
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: cerebro-job-
          labels:
            env: dev
        spec:
          backoffLimit: 0
          template:
            spec:
              restartPolicy: Never
              securityContext:
                runAsNonRoot: True
                runAsUser: 1000
              containers:
                - name: job
                  image: job:latest
                  #command: ["sleep", "infinity"]
                  imagePullPolicy: Never
                  env:
                    - name: TH_URL
                      value: http://thehive:9000
                    - name: TH_USER
                      value: user@thehive.local
                    - name: TH_PASSWORD
                      value: secret
  log.yml: |
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class : logging.StreamHandler
        formatter: simple
        level   : DEBUG
        stream  : ext://sys.stdout
    root:
      level: WARNING # max level set to the handler
      handlers: [console]
    loggers:
      uvicorn.error:
        level: INFO
        handlers: [console]
        propagate: no
      cerebro:
        level: DEBUG
        handlers: [console]
        propagate: no
      audit:
        level: INFO
        handlers: [console]
        propagate: no
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-runner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerebro
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cerebro
subjects:
  - kind: ServiceAccount
    name: cerebro
roleRef:
  kind: Role
  name: job-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  ports:
    - port: 8000
  selector:
    app: cerebro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      serviceAccountName: cerebro
      volumes:
        - name: config
          configMap:
            name: cerebro
      containers:
        - name: cerebro
          image: cerebro:latest
          command: ["uvicorn", "cerebro.api:app", "--host", "0.0.0.0", "--log-config", "/etc/log.yml"]
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/workers.yml
              subPath: workers.yml
              readOnly: true
            - name: config
              mountPath: /etc/log.yml
              subPath: log.yml
              readOnly: true
          env:
            - name: WORKER_CONFIG
              value: /etc/workers.yml
